import { HoloMember } from '@/types'
import { iconMapping } from './icon-mapping'

// アイコンパスを取得するヘルパー関数
function getIconPath(memberId: string): string {
  const fileName = iconMapping[memberId]
  return fileName
    ? `/images/hololive/icon/${fileName}`
    : `/images/hololive/icon/${memberId}.png`
}

export const holoMembers: HoloMember[] = [
  // 0期生
  {
    id: 'tokino_sora',
    name: 'Tokino Sora',
    nameJP: 'ときのそら',
    branch: 'JP',
    generation: '0期生',
    debut: '2017-09-07',
    description:
      'ホロライブの始まりとなったアイドルVtuber。歌とトークでファンを魅了する。',
    contentTypes: ['singing', 'chatting', 'gaming'],
    personality: ['calm', 'motherly'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('tokino_sora'),
    channelUrl: 'https://www.youtube.com/@TokinoSora',
    twitterUrl: 'https://twitter.com/tokino_sora',
    catchphrase: 'こんそめ〜！',
    recommendReason: 'アイドルらしい歌配信と温かいトークが魅力',
  },
  {
    id: 'roboco',
    name: 'Roboco',
    nameJP: 'ロボ子さん',
    branch: 'JP',
    generation: '0期生',
    debut: '2018-03-04',
    description:
      '高性能ロボットVtuber。ゲームが得意で、特にFPSでの腕前は圧巻。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['cool', 'natural'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['late_night'],
    streamLength: 'long',
    profileImage: getIconPath('roboco'),
    channelUrl: 'https://www.youtube.com/@Roboco',
    twitterUrl: 'https://twitter.com/robocosan',
    catchphrase: 'こんろぼ〜！',
    recommendReason: '深夜の長時間ゲーム配信でまったり楽しめる',
  },

  // 1期生
  {
    id: 'shirakami_fubuki',
    name: 'Shirakami Fubuki',
    nameJP: '白上フブキ',
    branch: 'JP',
    generation: '1期生',
    debut: '2018-06-01',
    description:
      '白いキツネのケモミミVtuber。配信の幅が広く、様々なコンテンツで楽しませる。',
    contentTypes: ['gaming', 'chatting', 'singing', 'collab'],
    personality: ['energetic', 'mischievous'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['afternoon', 'evening'],
    streamLength: 'varied',
    profileImage: getIconPath('shirakami_fubuki'),
    channelUrl: 'https://www.youtube.com/@ShirakamiFubuki',
    twitterUrl: 'https://twitter.com/shirakamifubuki',
    catchphrase: 'こんこんきーつね！',
    recommendReason: 'バラエティ豊かな配信とリスナーとの距離感が近い',
  },
  {
    id: 'natsuiro_matsuri',
    name: 'Natsuiro Matsuri',
    nameJP: '夏色まつり',
    branch: 'JP',
    generation: '1期生',
    debut: '2018-06-01',
    description:
      'チアリーダー衣装の元気いっぱいVtuber。高いテンションとトーク力が魅力。',
    contentTypes: ['gaming', 'chatting', 'singing'],
    personality: ['energetic', 'natural'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'medium',
    profileImage: getIconPath('natsuiro_matsuri'),
    channelUrl: 'https://www.youtube.com/@NatsuiroMatsuri',
    twitterUrl: 'https://twitter.com/natsuiromatsuri',
    catchphrase: 'わっしょい！',
    recommendReason: 'ハイテンションな配信でリスナーを巻き込む楽しさ',
  },

  // 2期生
  {
    id: 'minato_aqua',
    name: 'Minato Aqua',
    nameJP: '湊あくあ',
    branch: 'JP',
    generation: '2期生',
    debut: '2018-08-08',
    description:
      'ゲーマーメイドVtuber。ゲームの腕前はトップクラスで、特に音ゲーやFPSが得意。',
    contentTypes: ['gaming', 'singing'],
    personality: ['natural', 'cool'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'long',
    profileImage: getIconPath('minato_aqua'),
    channelUrl: 'https://www.youtube.com/@MinatoAqua',
    twitterUrl: 'https://twitter.com/minatoaqua',
    catchphrase: 'あくあ〜！',
    recommendReason: '高いゲームスキルと独特な天然さのギャップが魅力',
  },
  {
    id: 'murasaki_shion',
    name: 'Murasaki Shion',
    nameJP: '紫咲シオン',
    branch: 'JP',
    generation: '2期生',
    debut: '2018-08-17',
    description:
      '魔法使いの幼女（自称）Vtuber。可愛らしい見た目と小悪魔的な性格のギャップが魅力。',
    contentTypes: ['gaming', 'chatting', 'singing'],
    personality: ['mischievous', 'natural'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'short',
    profileImage: getIconPath('murasaki_shion'),
    channelUrl: 'https://www.youtube.com/@MurasakiShion',
    twitterUrl: 'https://twitter.com/murasakishionch',
    catchphrase: 'しおーん！',
    recommendReason: '気ままな配信スタイルと可愛らしい反応が癒し',
  },
  {
    id: 'nakiri_ayame',
    name: 'Nakiri Ayame',
    nameJP: '百鬼あやめ',
    branch: 'JP',
    generation: '2期生',
    debut: '2018-09-03',
    description:
      '鬼の女の子Vtuber。可愛らしい声と恥ずかしがり屋な性格で「余」という一人称が特徴。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['natural', 'calm'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'short',
    profileImage: getIconPath('nakiri_ayame'),
    channelUrl: 'https://www.youtube.com/@NakiriAyame',
    twitterUrl: 'https://twitter.com/nakiriayame',
    catchphrase: 'こんやっぴ〜！',
    recommendReason: '癒し系の声と自然体な配信スタイル',
  },
  {
    id: 'yuzuki_choco',
    name: 'Yuzuki Choco',
    nameJP: '癒月ちょこ',
    branch: 'JP',
    generation: '2期生',
    debut: '2018-09-05',
    description:
      '保健室の先生（悪魔）Vtuber。ASMRや癒し系配信が得意で、大人の魅力がある。',
    contentTypes: ['asmr', 'chatting', 'gaming'],
    personality: ['calm', 'motherly'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['late_night'],
    streamLength: 'medium',
    profileImage: getIconPath('yuzuki_choco'),
    channelUrl: 'https://www.youtube.com/@YuzukiChoco',
    twitterUrl: 'https://twitter.com/yuzukichococh',
    catchphrase: 'ちょこ〜ん！',
    recommendReason: '深夜のASMR配信で癒されたい人におすすめ',
  },
  {
    id: 'oozora_subaru',
    name: 'Oozora Subaru',
    nameJP: '大空スバル',
    branch: 'JP',
    generation: '2期生',
    debut: '2018-09-16',
    description:
      '体育会系の元気なVtuber。明るく爽やかなトークと笑い声が特徴的。',
    contentTypes: ['gaming', 'chatting', 'collab'],
    personality: ['energetic', 'witty'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('oozora_subaru'),
    channelUrl: 'https://www.youtube.com/@OozoraSubaru',
    twitterUrl: 'https://twitter.com/oozorasubaru',
    catchphrase: 'しゅばしゅば〜！',
    recommendReason: '明るいトークと豊かなリアクションで元気をもらえる',
  },

  // ゲーマーズ
  {
    id: 'ookami_mio',
    name: 'Ookami Mio',
    nameJP: '大神ミオ',
    branch: 'JP',
    generation: 'ゲーマーズ',
    debut: '2018-12-07',
    description:
      '狼のケモミミVtuber。優しいお母さん的な存在で、朝の占い配信が人気。',
    contentTypes: ['chatting', 'gaming', 'educational'],
    personality: ['motherly', 'calm'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['morning', 'afternoon'],
    streamLength: 'medium',
    profileImage: getIconPath('ookami_mio'),
    channelUrl: 'https://www.youtube.com/@OokamiMio',
    twitterUrl: 'https://twitter.com/ookamimio',
    catchphrase: 'こんみおーん！',
    recommendReason: '朝の占い配信と優しい雰囲気で一日をスタート',
  },
  {
    id: 'nekomata_okayu',
    name: 'Nekomata Okayu',
    nameJP: '猫又おかゆ',
    branch: 'JP',
    generation: 'ゲーマーズ',
    debut: '2019-04-06',
    description:
      '猫又の女の子Vtuber。落ち着いた低音ボイスと、ゆったりとした配信スタイルが特徴。',
    contentTypes: ['gaming', 'chatting', 'singing'],
    personality: ['calm', 'natural'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'long',
    profileImage: getIconPath('nekomata_okayu'),
    channelUrl: 'https://www.youtube.com/@NekomataOkayu',
    twitterUrl: 'https://twitter.com/nekomataokayu',
    catchphrase: 'もぐもぐ〜おかゆ〜！',
    recommendReason: '深夜のまったり配信で癒しの時間を提供',
  },
  {
    id: 'inugami_korone',
    name: 'Inugami Korone',
    nameJP: '戌神ころね',
    branch: 'JP',
    generation: 'ゲーマーズ',
    debut: '2019-10-01',
    description:
      '犬のケモミミVtuber。レトロゲームが大好きで、長時間の耐久配信も多い。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['energetic', 'natural'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['afternoon', 'evening', 'late_night'],
    streamLength: 'long',
    profileImage: getIconPath('inugami_korone'),
    channelUrl: 'https://www.youtube.com/@InugamiKorone',
    twitterUrl: 'https://twitter.com/inugamikorone',
    catchphrase: 'おあよ〜！',
    recommendReason: 'レトロゲーム愛と独特な言い回しが楽しい長時間配信',
  },

  // 3期生
  {
    id: 'usada_pekora',
    name: 'Usada Pekora',
    nameJP: '兎田ぺこら',
    branch: 'JP',
    generation: '3期生',
    debut: '2019-07-17',
    description:
      'うさ耳の女の子Vtuber。独特な笑い声「ぺこぺこぺこ」と、ゲーム実況での面白いリアクションが人気。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['energetic', 'mischievous'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'long',
    profileImage: getIconPath('usada_pekora'),
    channelUrl: 'https://www.youtube.com/@usadapekora',
    twitterUrl: 'https://twitter.com/usadapekora',
    catchphrase: 'こんぺこ！こんぺこ！こんぺこ〜！',
    recommendReason: 'エンターテイメント性の高いゲーム実況と独特なキャラクター',
  },
  {
    id: 'shiranui_flare',
    name: 'Shiranui Flare',
    nameJP: '不知火フレア',
    branch: 'JP',
    generation: '3期生',
    debut: '2019-08-07',
    description:
      'ハーフエルフのVtuber。落ち着いた配信スタイルと、歌唱力の高さが魅力。',
    contentTypes: ['gaming', 'singing', 'chatting'],
    personality: ['cool', 'calm'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'medium',
    profileImage: getIconPath('shiranui_flare'),
    channelUrl: 'https://www.youtube.com/@ShiranuiFlare',
    twitterUrl: 'https://twitter.com/shiranuiflare',
    catchphrase: 'こんぬい〜！',
    recommendReason: '落ち着いた雰囲気と安定感のある配信',
  },
  {
    id: 'shirogane_noel',
    name: 'Shirogane Noel',
    nameJP: '白銀ノエル',
    branch: 'JP',
    generation: '3期生',
    debut: '2019-08-08',
    description: '騎士団長のVtuber。優しい性格と、ASMR配信での囁き声が人気。',
    contentTypes: ['asmr', 'gaming', 'chatting'],
    personality: ['motherly', 'natural'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'medium',
    profileImage: getIconPath('shirogane_noel'),
    channelUrl: 'https://www.youtube.com/@ShiroganeNoel',
    twitterUrl: 'https://twitter.com/shiroganenoel',
    catchphrase: 'のえる〜！',
    recommendReason: 'ASMR配信と温かい人柄で心地よい時間を提供',
  },
  {
    id: 'houshou_marine',
    name: 'Houshou Marine',
    nameJP: '宝鐘マリン',
    branch: 'JP',
    generation: '3期生',
    debut: '2019-08-11',
    description:
      '海賊船長のVtuber。トーク力が非常に高く、大人向けのユーモアも交えた配信が特徴。',
    contentTypes: ['chatting', 'singing', 'drawing'],
    personality: ['witty', 'energetic'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('houshou_marine'),
    channelUrl: 'https://www.youtube.com/@HoushouMarine',
    twitterUrl: 'https://twitter.com/houshoumarine',
    catchphrase: 'Ahoy!',
    recommendReason: '抜群のトーク力と豊富な話題で飽きさせない配信',
  },

  // 4期生
  {
    id: 'amane_kanata',
    name: 'Amane Kanata',
    nameJP: '天音かなた',
    branch: 'JP',
    generation: '4期生',
    debut: '2019-12-27',
    description:
      '天使のVtuber。高い歌唱力と、努力家な一面が魅力的。握力50kgの怪力天使。',
    contentTypes: ['singing', 'gaming', 'chatting'],
    personality: ['energetic', 'natural'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('amane_kanata'),
    channelUrl: 'https://www.youtube.com/@AmaneKanata',
    twitterUrl: 'https://twitter.com/amanekanatach',
    catchphrase: 'こんかなた〜！',
    recommendReason: '高い歌唱力と前向きな姿勢に元気をもらえる',
  },
  {
    id: 'tsunomaki_watame',
    name: 'Tsunomaki Watame',
    nameJP: '角巻わため',
    branch: 'JP',
    generation: '4期生',
    debut: '2019-12-29',
    description:
      '羊のVtuber。歌配信や作曲活動に力を入れており、オリジナル曲も多数リリース。',
    contentTypes: ['singing', 'chatting', 'music_creation'],
    personality: ['calm', 'motherly'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['morning', 'late_night'],
    streamLength: 'long',
    profileImage: getIconPath('tsunomaki_watame'),
    channelUrl: 'https://www.youtube.com/@TsunomakiWatame',
    twitterUrl: 'https://twitter.com/tsunomakiwatame',
    catchphrase: 'どどどど〜！',
    recommendReason: '朝配信と深夜の歌枠で一日の始まりと終わりを彩る',
  },
  {
    id: 'tokoyami_towa',
    name: 'Tokoyami Towa',
    nameJP: '常闇トワ',
    branch: 'JP',
    generation: '4期生',
    debut: '2020-01-03',
    description:
      '小悪魔のVtuber。可愛らしい見た目とは裏腹に、FPSゲームの腕前が高い。',
    contentTypes: ['gaming', 'singing', 'chatting'],
    personality: ['cool', 'natural'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'long',
    profileImage: getIconPath('tokoyami_towa'),
    channelUrl: 'https://www.youtube.com/@TokoyamiTowa',
    twitterUrl: 'https://twitter.com/tokoyamitowa',
    catchphrase: 'こんやっぴ〜！',
    recommendReason: 'FPSの高い実力と可愛らしい反応のギャップ',
  },
  {
    id: 'himemori_luna',
    name: 'Himemori Luna',
    nameJP: '姫森ルーナ',
    branch: 'JP',
    generation: '4期生',
    debut: '2020-01-04',
    description: 'お姫様のVtuber。「なのら〜」という語尾と、甘えた声が特徴的。',
    contentTypes: ['gaming', 'chatting', 'singing'],
    personality: ['natural', 'mischievous'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'short',
    profileImage: getIconPath('himemori_luna'),
    channelUrl: 'https://www.youtube.com/@HimemoriLuna',
    twitterUrl: 'https://twitter.com/himemoriluna',
    catchphrase: 'んなっ！',
    recommendReason: '独特なキャラクターとリスナーとの掛け合いが楽しい',
  },

  // 5期生
  {
    id: 'yukihana_lamy',
    name: 'Yukihana Lamy',
    nameJP: '雪花ラミィ',
    branch: 'JP',
    generation: '5期生',
    debut: '2020-08-12',
    description: '雪の国のお姫様Vtuber。お酒配信と、優しい声での雑談が人気。',
    contentTypes: ['chatting', 'asmr', 'gaming'],
    personality: ['calm', 'motherly'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['late_night'],
    streamLength: 'long',
    profileImage: getIconPath('yukihana_lamy'),
    channelUrl: 'https://www.youtube.com/@YukihanaLamy',
    twitterUrl: 'https://twitter.com/yukihanalamy',
    catchphrase: 'こんらみ〜！',
    recommendReason: '深夜の雑談配信で大人の癒し時間を提供',
  },
  {
    id: 'momosuzu_nene',
    name: 'Momosuzu Nene',
    nameJP: '桃鈴ねね',
    branch: 'JP',
    generation: '5期生',
    debut: '2020-08-13',
    description:
      'アイドルを目指すVtuber。明るく元気な性格と、高い歌唱力が魅力。',
    contentTypes: ['singing', 'chatting', 'gaming'],
    personality: ['energetic', 'natural'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('momosuzu_nene'),
    channelUrl: 'https://www.youtube.com/@MomosuzuNene',
    twitterUrl: 'https://twitter.com/momosuzunene',
    catchphrase: 'ねねっち〜！',
    recommendReason: 'アイドルらしい明るさと親しみやすさ',
  },
  {
    id: 'shishiro_botan',
    name: 'Shishiro Botan',
    nameJP: '獅白ぼたん',
    branch: 'JP',
    generation: '5期生',
    debut: '2020-08-14',
    description:
      '白獅子のVtuber。FPSゲームのプロ級の腕前と、落ち着いた大人の魅力がある。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['cool', 'calm'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['afternoon', 'evening'],
    streamLength: 'long',
    profileImage: getIconPath('shishiro_botan'),
    channelUrl: 'https://www.youtube.com/@ShishiroBotan',
    twitterUrl: 'https://twitter.com/shishirobotan',
    catchphrase: 'ぽいぽい〜！',
    recommendReason: 'プロ級のFPS実力と落ち着いた実況',
  },
  {
    id: 'omaru_polka',
    name: 'Omaru Polka',
    nameJP: '尾丸ポルカ',
    branch: 'JP',
    generation: '5期生',
    debut: '2020-08-16',
    description:
      'サーカス団のVtuber。高いエンターテイメント性と、多彩な声真似が特徴。',
    contentTypes: ['chatting', 'gaming', 'singing'],
    personality: ['energetic', 'witty'],
    streamingStyle: 'performance_focused',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'varied',
    profileImage: getIconPath('omaru_polka'),
    channelUrl: 'https://www.youtube.com/@OmaruPolka',
    twitterUrl: 'https://twitter.com/omarupolka',
    catchphrase: 'ポルカおるか〜？',
    recommendReason: 'サーカスのような賑やかで楽しい配信',
  },

  // 6期生（holoX）
  {
    id: 'laplus_darknesss',
    name: 'La+ Darknesss',
    nameJP: 'ラプラス・ダークネス',
    branch: 'JP',
    generation: 'holoX',
    debut: '2021-11-26',
    description:
      '秘密結社holoXの総帥。小柄だが威厳ある（？）振る舞いとゲーム配信が人気。',
    contentTypes: ['gaming', 'chatting'],
    personality: ['mischievous', 'energetic'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('laplus_darknesss'),
    channelUrl: 'https://www.youtube.com/@LaplusDarknesss',
    twitterUrl: 'https://twitter.com/laplusdarknesss',
    catchphrase: 'YMD！YMD！',
    recommendReason: '小悪魔的な魅力とゲーム実況の面白さ',
  },
  {
    id: 'takane_lui',
    name: 'Takane Lui',
    nameJP: '鷹嶺ルイ',
    branch: 'JP',
    generation: 'holoX',
    debut: '2021-11-27',
    description:
      '秘密結社holoXの幹部。クールな見た目と優しい性格のギャップが魅力。',
    contentTypes: ['chatting', 'singing', 'gaming'],
    personality: ['cool', 'motherly'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['afternoon', 'evening'],
    streamLength: 'medium',
    profileImage: getIconPath('takane_lui'),
    channelUrl: 'https://www.youtube.com/@TakaneLui',
    twitterUrl: 'https://twitter.com/takanelui',
    catchphrase: 'こんルイ〜！',
    recommendReason: 'お姉さん的な優しさとクールな魅力',
  },
  {
    id: 'hakui_koyori',
    name: 'Hakui Koyori',
    nameJP: '博衣こより',
    branch: 'JP',
    generation: 'holoX',
    debut: '2021-11-28',
    description:
      '秘密結社holoXの研究者。朝活配信と長時間配信が多く、研究熱心な性格。',
    contentTypes: ['chatting', 'gaming', 'educational'],
    personality: ['energetic', 'witty'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['morning', 'afternoon', 'evening'],
    streamLength: 'long',
    profileImage: getIconPath('hakui_koyori'),
    channelUrl: 'https://www.youtube.com/@HakuiKoyori',
    twitterUrl: 'https://twitter.com/hakuikoyori',
    catchphrase: 'こよりの朝こよ〜！',
    recommendReason: '朝活配信と研究熱心な長時間配信',
  },
  {
    id: 'sakamata_chloe',
    name: 'Sakamata Chloe',
    nameJP: '沙花叉クロヱ',
    branch: 'JP',
    generation: 'holoX',
    debut: '2021-11-29',
    description:
      '秘密結社holoXの掃除屋。シャチのフードが特徴的で、歌唱力が高い。',
    contentTypes: ['singing', 'chatting', 'gaming'],
    personality: ['cool', 'natural'],
    streamingStyle: 'laid_back',
    languages: ['JP'],
    typicalStreamTimes: ['evening', 'late_night'],
    streamLength: 'medium',
    profileImage: getIconPath('sakamata_chloe'),
    channelUrl: 'https://www.youtube.com/@SakamataChloe',
    twitterUrl: 'https://twitter.com/sakamatachloe',
    catchphrase: 'ばんちゃ〜！',
    recommendReason: '独特な声と高い歌唱力',
  },
  {
    id: 'kazama_iroha',
    name: 'Kazama Iroha',
    nameJP: '風真いろは',
    branch: 'JP',
    generation: 'holoX',
    debut: '2021-11-30',
    description:
      '秘密結社holoXの用心棒。忍者らしい俊敏さと、意外と天然な一面がある。',
    contentTypes: ['gaming', 'chatting', 'singing'],
    personality: ['natural', 'energetic'],
    streamingStyle: 'chat_interactive',
    languages: ['JP'],
    typicalStreamTimes: ['evening'],
    streamLength: 'medium',
    profileImage: getIconPath('kazama_iroha'),
    channelUrl: 'https://www.youtube.com/@KazamaIroha',
    twitterUrl: 'https://twitter.com/kazamairohach',
    catchphrase: 'でござる〜！',
    recommendReason: '忍者キャラと天然な反応のギャップ',
  },
]
